S-91214 added support for new tables Asset and AssetNow
versionone/scripts pull request #32
Opened 2023-03-16 17:39 UTC by lremedi

2023-10-18 12:53 UTC, lremedi commented on fixes/D-07213-meta-id-conflict.sql
> +end
That's right, it works perfectly.
![image](https://github.com/versionone/scripts/assets/545541/d3cecb45-a76c-4f1c-ae9e-9bff2679cf39)

2023-11-02 23:10 UTC, pmamut requested changes

2023-11-03 13:46 UTC, lremedi commented on fixes/fix-collations.sql
> +	exec dbo._ForceBinaryCollation 'AssetAudit.AssetType'
![image](https://github.com/versionone/scripts/assets/545541/3cded307-c9f7-43e4-9e31-7cf326b34f8f)
I didn't know about it but `INFORMATION_SCHEMA.COLUMNS ` also contains views columns too.
Good learning

2023-11-07 00:07 UTC, merged

2023-11-07 01:18 UTC, pmamut commented on fixes/fix-collations.sql
> +	exec dbo._ForceBinaryCollation 'AssetAudit.AssetType'
point being, no need for conditional execution of `exec dbo._ForceBinaryCollation 'AssetAudit.AssetType`