Commit lag script with decimal minute precision
versionone/scripts pull request #34
Opened 2023-10-13 13:58 UTC by lremedi

2023-10-14 03:48 UTC, pmamut requested changes
not quite

2023-10-14 03:48 UTC, pmamut commented on troubleshooting/current-commit-lag.sql
> +Latest = AuditStamp,
`Occurred`, not `Latest`

2023-10-14 03:48 UTC, pmamut commented on troubleshooting/current-commit-lag.sql
> +Lag = CONVERT(FLOAT,getdate()-CommitStamp) * 24 * 60 --Decimal Minutes
`getutcdate()`

2023-10-14 03:48 UTC, pmamut commented on troubleshooting/current-commit-lag.sql
> +Behind = CONVERT(FLOAT,CommitStamp-AuditStamp) * 24 * 60, --Decimal Minutes
`CycleTime`, not `Behind` - this is how long it took to process an Audit to produce this Commit

2023-10-14 03:48 UTC, pmamut commented on troubleshooting/current-commit-lag.sql
> +)
```
,
A as (select top 1 * from dbo.Audit order by ID desc)
```

2023-10-14 03:48 UTC, pmamut commented on troubleshooting/current-commit-lag.sql
> +Behind = CONVERT(FLOAT,CommitStamp-AuditStamp) * 24 * 60, --Decimal Minutes
also want `Behind = A.ChangeDateUTC - AuditStamp`

2023-10-16 01:19 UTC, pmamut commented
please also check https://github.com/versionone/scripts/blob/master/troubleshooting/current-activity-lag.sql#L6 sort - should probably also be `CommitStamp` or `CheckpointNumber`

2023-10-16 01:22 UTC, pmamut commented
and https://github.com/versionone/scripts/blob/master/troubleshooting/current-activity-lag.sql#L7 probably needs to specify `BucketId` and `StreamId` https://github.com/versionone/Core/blob/23.2/VersionOne/EventStore/MetaStream/MetaStreamService.cs#L16-L18

2023-10-19 15:12 UTC, lremedi commented
> and https://github.com/versionone/scripts/blob/master/troubleshooting/current-activity-lag.sql#L7 probably needs to specify `BucketId` and `StreamId` https://github.com/versionone/Core/blob/23.2/VersionOne/EventStore/MetaStream/MetaStreamService.cs#L16-L18

https://github.com/versionone/scripts/pull/34/files#diff-f13e9d69147acb2d590a84968b59ca3216d23caf49ef119fa8f185b642c2ab09R9

2023-10-19 15:15 UTC, lremedi commented
Better execution plans for current-activity-lag after adding  `BucketId` and `StreamId` filters and ordering by `CheckpointNumber`

![image](https://github.com/versionone/scripts/assets/545541/a77dba9b-4fc4-4ac7-a93b-1170b3467da7)

2023-10-19 15:21 UTC, merged